### ISSUE TITLE
Question: Can I block all service except some specific service with this program?

### ISSUE THREAD

**Issue by GreatBahram** [eglooca/netify-daemon#14]
Hi
I have tried to do this with `ndpi-netfilter` but it was hopeless, I'm searching open source DPI to use it as a whitelist, I mean block all traffic by default and allow some specific protocol. 
The problem with `ndpi-netfilter` is when you drop all it actually means you don't allow any connection to be established, iptables drops all initial packets (`SYN`, `SYN-ACK`, `ACK`).

**Comment by pcbaldwin** [comment]
Hi GreatBahram,

That's a tricky problem.  In order to analyze traffic flow with DPI, a bunch of packets (e.g. 20) need to pass through.   It's not only the SYN, SYN-ACK and ACK part of the TCP conversation, but also a few more!  UDP and other protocols are a different beast.  Regardless, that's the nature of DPI - we need packets in order to do the inspection.

In theory, the traffic flow could go something like:

- Allow connection A
- Do the DPI inspection on connection A
- If not whitelisted, drop connection A

There's a timing issue there of course.  For example, an HTTP connection might have been able to get some data before it was dropped. 

You should know that Netifyd provides the DPI and just the DPI ...  it does not provide any kind of firewalling or QoS.  Instead, you can build a hook into the live Netifyd JSON output to do what's needed in a 3rd party software package (firewall, QoS, charts... anything really).

**Comment by GreatBahram** [comment]
@pcbaldwin 
Thank you I really appreciate your explanation. The more I research about how to use DPI as white-list the more I realize maybe they aren't designed to use as white-list. I couldn't find any enterprise device that support DPI as white-list as well.
Anyway, Thank you a lot dude
